### ISSUE TITLE
Virtual sensors and real sensors cannot be read

### ISSUE THREAD

**Issue by zsq19958629** [RobTillaart/DS18B20_INT#1]
I have 2 Arduino, the first one runs the OneWireHub library, and the virtual one is a DS18B20 device. The second block runs DS18B20_INT to read the first block of UNO virtual DS18b20.
However, the temperature could not be read successfully.
The virtual 18B20 is normally read by the OneWire library.
OneWire can also read it using a real 18B20 sensor. But DS18B20_INT cannot read the virtual sensor and the physical sensor.
PLS help me。
```
#include "DS18B20_INT.h"

#define ONE_WIRE_BUS 5

OneWire oneWire(ONE_WIRE_BUS);
DS18B20_INT sensor(&oneWire);

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);
}


void loop()
{
  if (sensor.begin())
  {
    int n = 0;
    sensor.requestTemperatures();
    delay(1000);
    while (!sensor.isConversionComplete()) n++;
    int t = sensor.getTempC();

    Serial.print(n);
    Serial.print("\t");
    Serial.println(t);
    Serial.println();
    delay(1000);
  }
  else
  {
    Serial.println("Err");
  }
}
```
Log：
> 17:39:20.228 -> 0	-1
> 17:39:20.228 -> 
> 17:39:22.277 -> 0	-1
> 17:39:22.277 -> 
> 17:39:24.280 -> 0	-1
THX

OneWireHub：
https://github.com/orgua/OneWireHub
OneWire：
https://www.pjrc.com/teensy/td_libs_OneWire.html

**Comment by RobTillaart** [comment]
Hi, can you tell more about a virtual 18B20 ?
Is this a simulator or ?  ==> YES (found that)


1. From the log it is clear that the DS18B20_INT library is not blocking.
can you confirm?

2. Can the virtual DS18B20 be read either by
https://github.com/milesburton/Arduino-Temperature-Control-Library
or
https://github.com/RobTillaart/DS18B20_RT

3.  After the delay(1000) the conversion is complete as the var N is zero
so that call seems to work correctly.
What does the log give if you comment the delay(1000); line?

4. The temperature read is -1 , what did you expect? what should it be?

5. Do you have grounds connected?

6. Do you have a pull up resistor on the oneWire bus?

7. The fact that begin() returns true, shows the library finds a valid address?
You might add some print statements to dump the found address so you can check if this is the one expected.

**Comment by zsq19958629** [comment]
I'm so sorry!
This is my own hardware problem, the target MCU should pull up 4.7K resistor, but when I designed the PCB, it was designed to pull down 4.7K resistor.
I'm very sorry for the trouble.

Change the pull-down resistor to a pull-up resistor and everything works fine.

**Comment by RobTillaart** [comment]
Good to hear 👍
